services:
  agent:
    build: ./app
    network_mode: "host"  # ← přidej tento řádek
    volumes:
      - ./app:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
