version: '3'
services:
  server:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      - LLM_SERVER_URL=http://llm:8001/generate
  llm:
    build: ./llm_service
    volumes:
      - ./app/models:/app/models
    ports:
      - "8001:8001"
